services:
  mp-mongo:
    image: mongo:8.0 
    container_name: mp-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo-data:/data/db
      - ./data/mongo-config:/data/configdb
  grafana: #admin - admin
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana-storage:/var/lib/grafana
  mp-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres-storage:/var/lib/postgresql
    ports:
      - "5332:5432"
#  metabase:
#    image: metabase/metabase:latest
#    restart: always
#    environment:
#      MB_DB_TYPE: "postgres"
#      MB_DB_DBNAME: "metabase"
#      MB_DB_PORT: "5432"
#      MB_DB_USER: "dofus"
#      MB_DB_PASS: "password"
#      MB_DB_HOST: "docker-mp-postgres-1"
#      MB_PASSWORD_COMPLEXITY: strong
#      MB_PASSWORD_LENGTH: 3
#      JAVA_TIMEZONE: America/Toronto
#    ports:
#      - 127.0.0.1:3001:3000

# 1WachtW1!